export const playerData = {
  attackers: [
    {
      href: "/players/lionel-messi",
      firstName: "Lionel",
      lastName: "Messi",
      position: "RW",
      number: 10,
      team: "PSG",
      age: 35,
      foot: "left",
      careerStats: {
        apps: 176,
        goals: 104,
        assists: 56,
      },
      tournamentStats: {
        gamesPlayed: 7,
        asSubstitute: 0,
        goals: 7,
        assists: 3,
        averageRating: 8.3,
        cards: {
          yellow: 1,
          red: 0,
        },
        passes: {
          total: 347,
          key: 21,
          accuracy: 42,
        },
        dribbles: {
          attempts: 27,
          success: 15,
        },
        duels: {
          total: 98,
          won: 44,
        },
        shots: {
          total: 29,
          on: 18,
        },
        fouls: {
          drawn: 22,
          committed: 10,
        },
        minutesPlayed: 690,
      },
    },
    {
      href: "/players/angel-dimaria",
      firstName: "Angel",
      lastName: "Di Maria",
      position: "LW",
      number: 11,
      team: "Juventus",
      age: 34,
      foot: "left",
      careerStats: {
        apps: 133,
        goals: 28,
        assists: 29,
      },
      tournamentStats: {
        gamesPlayed: 5,
        asSubstitute: 1,
        goals: 1,
        assists: 1,
        averageRating: 7.3,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 138,
          key: 10,
          accuracy: 24,
        },
        dribbles: {
          attempts: 21,
          success: 13,
        },
        duels: {
          total: 40,
          won: 23,
        },
        shots: {
          total: 4,
          on: 3,
        },
        fouls: {
          drawn: 7,
          committed: 0,
        },
        minutesPlayed: 290,
      },
    },
    {
      href: "/players/julian-alvarez",
      firstName: "Julian",
      lastName: "Alvarez",
      position: "ST",
      number: 9,
      team: "Manchester City",
      age: 22,
      foot: "right",
      careerStats: {
        apps: 23,
        goals: 7,
        assists: 1,
      },
      tournamentStats: {
        gamesPlayed: 7,
        asSubstitute: 2,
        goals: 4,
        assists: 0,
        averageRating: 7.0,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 116,
          key: 3,
          accuracy: 12,
        },
        dribbles: {
          attempts: 3,
          success: 0,
        },
        duels: {
          total: 40,
          won: 8,
        },
        shots: {
          total: 9,
          on: 8,
        },
        fouls: {
          drawn: 2,
          committed: 13,
        },
        minutesPlayed: 467,
      },
    },
    {
      href: "/players/lautaro-martinez",
      firstName: "Lautaro",
      lastName: "Martinez",
      position: "ST",
      number: 22,
      team: "Inter Milan",
      age: 25,
      foot: "right",
      careerStats: {
        apps: 49,
        goals: 20,
        assists: 7,
      },
      tournamentStats: {
        gamesPlayed: 6,
        asSubstitute: 4,
        goals: 0,
        assists: 0,
        averageRating: 6.4,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 63,
          key: 1,
          accuracy: 7,
        },
        dribbles: {
          attempts: 5,
          success: 2,
        },
        duels: {
          total: 29,
          won: 13,
        },
        shots: {
          total: 11,
          on: 4,
        },
        fouls: {
          drawn: 5,
          committed: 1,
        },
        minutesPlayed: 238,
      },
    },
    {
      href: "/players/paulo-dybala",
      firstName: "Paulo",
      lastName: "Dybala",
      position: "ST",
      number: 21,
      team: "AS Roma",
      age: 30,
      foot: "left",
      careerStats: {
        apps: 38,
        goals: 3,
        assists: 7,
      },
      tournamentStats: {
        gamesPlayed: 2,
        asSubstitute: 2,
        goals: 0,
        assists: 0,
        averageRating: 7.0,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 12,
          key: 1,
          accuracy: 4,
        },
        dribbles: {
          attempts: 2,
          success: 1,
        },
        duels: {
          total: 11,
          won: 7,
        },
        shots: {
          total: 0,
          on: 0,
        },
        fouls: {
          drawn: 0,
          committed: 1,
        },
        minutesPlayed: 16,
      },
    },
    {
      href: "/players/angel-correa",
      firstName: "Angel",
      lastName: "Correa",
      position: "ST",
      number: 15,
      team: "Atletico Madrid",
      age: 27,
      foot: "right",
      careerStats: {
        apps: 23,
        goals: 3,
        assists: 0,
      },
      tournamentStats: {
        gamesPlayed: 1,
        asSubstitute: 1,
        goals: 0,
        assists: 0,
        averageRating: 6.7,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 3,
          key: 0,
          accuracy: 3,
        },
        dribbles: {
          attempts: 0,
          success: 0,
        },
        duels: {
          total: 2,
          won: 2,
        },
        shots: {
          total: 0,
          on: 0,
        },
        fouls: {
          drawn: 1,
          committed: 0,
        },
        minutesPlayed: 4,
      },
    },
  ],
  midfielders: [
    {
      href: "/players/enzo-fernandez",
      firstName: "Enzo",
      lastName: "Fernandez",
      position: "CM",
      number: 24,
      team: "Benfica",
      age: 21,
      foot: "right",
      careerStats: {
        apps: 15,
        goals: 3,
        assists: 2,
      },
      tournamentStats: {
        gamesPlayed: 7,
        asSubstitute: 2,
        goals: 1,
        assists: 1,
        averageRating: 7.2,
        cards: {
          yellow: 1,
          red: 0,
        },
        passes: {
          total: 468,
          key: 6,
          accuracy: 58,
        },
        dribbles: {
          attempts: 5,
          success: 3,
        },
        duels: {
          total: 68,
          won: 40,
        },
        shots: {
          total: 6,
          on: 3,
        },
        fouls: {
          drawn: 6,
          committed: 7,
        },
        tackles: {
          total: 22,
          blocks: 1,
          interceptions: 3,
        },
        minutesPlayed: 563,
      },
    },
    {
      href: "/players/rodrigo-depaul",
      firstName: "Rodrigo",
      lastName: "De Paul",
      position: "CM",
      number: 7,
      team: "Atletico Madrid",
      age: 28,
      foot: "right",
      careerStats: {
        apps: 56,
        goals: 2,
        assists: 7,
      },
      tournamentStats: {
        gamesPlayed: 7,
        asSubstitute: 0,
        goals: 0,
        assists: 0,
        averageRating: 6.9,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 539,
          key: 7,
          accuracy: 66,
        },
        dribbles: {
          attempts: 5,
          success: 3,
        },
        duels: {
          total: 55,
          won: 29,
        },
        shots: {
          total: 5,
          on: 3,
        },
        fouls: {
          drawn: 15,
          committed: 7,
        },
        tackles: {
          total: 11,
          blocks: 0,
          interceptions: 7,
        },
        minutesPlayed: 602,
      },
    },
    {
      href: "/players/alexis-mac-allister",
      firstName: "Alexis",
      lastName: "Mac Allister",
      position: "CM",
      number: 20,
      team: "Brighton",
      age: 24,
      foot: "right",
      careerStats: {
        apps: 19,
        goals: 1,
        assists: 2,
      },
      tournamentStats: {
        gamesPlayed: 6,
        asSubstitute: 0,
        goals: 1,
        assists: 1,
        averageRating: 7.1,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 263,
          key: 8,
          accuracy: 39,
        },
        dribbles: {
          attempts: 6,
          success: 4,
        },
        duels: {
          total: 57,
          won: 31,
        },
        shots: {
          total: 7,
          on: 4,
        },
        fouls: {
          drawn: 13,
          committed: 1,
        },
        tackles: {
          total: 9,
          blocks: 1,
          interceptions: 3,
        },
        minutesPlayed: 555,
      },
    },
    {
      href: "/players/leandro-paredes",
      firstName: "Leandro",
      lastName: "Paredes",
      position: "CM",
      number: 5,
      team: "Juventus",
      age: 28,
      foot: "right",
      careerStats: {
        apps: 56,
        goals: 5,
        assists: 7,
      },
      tournamentStats: {
        gamesPlayed: 5,
        asSubstitute: 3,
        goals: 0,
        assists: 0,
        averageRating: 7.0,
        cards: {
          yellow: 2,
          red: 0,
        },
        passes: {
          total: 244,
          key: 2,
          accuracy: 45,
        },
        dribbles: {
          attempts: 1,
          success: 0,
        },
        duels: {
          total: 26,
          won: 19,
        },
        shots: {
          total: 1,
          on: 1,
        },
        fouls: {
          drawn: 5,
          committed: 6,
        },
        tackles: {
          total: 10,
          blocks: 0,
          interceptions: 3,
        },
        minutesPlayed: 224,
      },
    },
    {
      href: "/players/exequiel-palacios",
      firstName: "Exequiel",
      lastName: "Palacios",
      position: "CM",
      number: 14,
      team: "Bayer Leverkusen",
      age: 25,
      foot: "right",
      careerStats: {
        apps: 27,
        goals: 0,
        assists: 4,
      },
      tournamentStats: {
        gamesPlayed: 3,
        asSubstitute: 3,
        goals: 0,
        assists: 0,
        averageRating: 6.4,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 27,
          key: 1,
          accuracy: 8,
        },
        dribbles: {
          attempts: 1,
          success: 0,
        },
        duels: {
          total: 10,
          won: 3,
        },
        shots: {
          total: 0,
          on: 0,
        },
        fouls: {
          drawn: 3,
          committed: 2,
        },
        tackles: {
          total: 0,
          blocks: 0,
          interceptions: 2,
        },
        minutesPlayed: 47,
      },
    },
    {
      href: "/players/guido-rodriguez",
      firstName: "Guido",
      lastName: "Rodriguez",
      position: "CM",
      number: 18,
      team: "Real Betis",
      age: 28,
      foot: "right",
      careerStats: {
        apps: 29,
        goals: 1,
        assists: 1,
      },
      tournamentStats: {
        gamesPlayed: 1,
        asSubstitute: 0,
        goals: 0,
        assists: 0,
        averageRating: 7.0,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 64,
          key: 0,
          accuracy: 54,
        },
        dribbles: {
          attempts: 0,
          success: 0,
        },
        duels: {
          total: 3,
          won: 3,
        },
        shots: {
          total: 0,
          on: 0,
        },
        fouls: {
          drawn: 0,
          committed: 0,
        },
        tackles: {
          total: 2,
          blocks: 1,
          interceptions: 0,
        },
        minutesPlayed: 57,
      },
    },
    {
      href: "/players/alejandro-gomez",
      firstName: "Alejandro",
      lastName: "Gomez",
      position: "CAM",
      number: 17,
      team: "Sevilla",
      age: 34,
      foot: "right",
      careerStats: {
        apps: 16,
        goals: 3,
        assists: 4,
      },
      tournamentStats: {
        gamesPlayed: 2,
        asSubstitute: 0,
        goals: 0,
        assists: 0,
        averageRating: 6.8,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 56,
          key: 0,
          accuracy: 26,
        },
        dribbles: {
          attempts: 1,
          success: 1,
        },
        duels: {
          total: 12,
          won: 9,
        },
        shots: {
          total: 2,
          on: 0,
        },
        fouls: {
          drawn: 5,
          committed: 1,
        },
        tackles: {
          total: 2,
          blocks: 0,
          interceptions: 1,
        },
        minutesPlayed: 109,
      },
    },
    {
      href: "/players/thiago-almada",
      firstName: "Thiago",
      lastName: "Almada",
      position: "CAM",
      number: 16,
      team: "Atlanta United",
      age: 21,
      foot: "right",
      careerStats: {
        apps: 4,
        goals: 1,
        assists: 0,
      },
      tournamentStats: {
        gamesPlayed: 1,
        asSubstitute: 1,
        goals: 0,
        assists: 0,
        averageRating: 6.9,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 13,
          key: 1,
          accuracy: 13,
        },
        dribbles: {
          attempts: 0,
          success: 0,
        },
        duels: {
          total: 0,
          won: 0,
        },
        shots: {
          total: 0,
          on: 0,
        },
        fouls: {
          drawn: 0,
          committed: 0,
        },
        tackles: {
          total: 0,
          blocks: 0,
          interceptions: 0,
        },
        minutesPlayed: 6,
      },
    },
  ],
  defenders: [
    {
      href: "/players/cristian-romero",
      firstName: "Cristian",
      lastName: "Romero",
      position: "CB",
      number: 13,
      team: "Tottenham",
      age: 24,
      foot: "right",
      careerStats: {
        apps: 24,
        goals: 2,
        assists: 0,
      },
      tournamentStats: {
        gamesPlayed: 7,
        asSubstitute: 1,
        goals: 0,
        assists: 0,
        averageRating: 6.8,
        cards: {
          yellow: 2,
          red: 0,
        },
        passes: {
          total: 373,
          key: 0,
          accuracy: 47,
        },
        dribbles: {
          attempts: 1,
          success: 1,
        },
        duels: {
          total: 45,
          won: 21,
        },
        shots: {
          total: 0,
          on: 0,
        },
        fouls: {
          drawn: 3,
          committed: 12,
        },
        tackles: {
          total: 5,
          blocks: 4,
          interceptions: 4,
        },
        minutesPlayed: 548,
      },
    },
    {
      href: "/players/nicolas-otamendi",
      firstName: "Nicolas",
      lastName: "Otamendi",
      position: "CB",
      number: 19,
      team: "Benfica",
      age: 34,
      foot: "right",
      careerStats: {
        apps: 105,
        goals: 4,
        assists: 3,
      },
      tournamentStats: {
        gamesPlayed: 7,
        asSubstitute: 0,
        goals: 0,
        assists: 0,
        averageRating: 6.9,
        cards: {
          yellow: 2,
          red: 0,
        },
        passes: {
          total: 575,
          key: 2,
          accuracy: 75,
        },
        dribbles: {
          attempts: 0,
          success: 0,
        },
        duels: {
          total: 65,
          won: 36,
        },
        shots: {
          total: 1,
          on: 0,
        },
        fouls: {
          drawn: 5,
          committed: 13,
        },
        tackles: {
          total: 10,
          blocks: 2,
          interceptions: 9,
        },
        minutesPlayed: 690,
      },
    },
    {
      href: "/players/marcos-acuna",
      firstName: "Marcos",
      lastName: "Acuna",
      position: "LB",
      number: 8,
      team: "Sevilla",
      age: 32,
      foot: "left",
      careerStats: {
        apps: 53,
        goals: 0,
        assists: 7,
      },
      tournamentStats: {
        gamesPlayed: 6,
        asSubstitute: 2,
        goals: 0,
        assists: 0,
        averageRating: 7.0,
        cards: {
          yellow: 3,
          red: 0,
        },
        passes: {
          total: 173,
          key: 5,
          accuracy: 23,
        },
        dribbles: {
          attempts: 6,
          success: 2,
        },
        duels: {
          total: 53,
          won: 28,
        },
        shots: {
          total: 2,
          on: 0,
        },
        fouls: {
          drawn: 9,
          committed: 9,
        },
        tackles: {
          total: 12,
          blocks: 1,
          interceptions: 2,
        },
        minutesPlayed: 374,
      },
    },
    {
      href: "/players/gonzalo-montiel",
      firstName: "Gonzalo",
      lastName: "Montiel",
      position: "RB",
      number: 4,
      team: "Sevilla",
      age: 25,
      foot: "right",
      careerStats: {
        apps: 23,
        goals: 1,
        assists: 0,
      },
      tournamentStats: {
        gamesPlayed: 4,
        asSubstitute: 3,
        goals: 0,
        assists: 0,
        averageRating: 6.6,
        cards: {
          yellow: 3,
          red: 0,
        },
        passes: {
          total: 66,
          key: 3,
          accuracy: 14,
        },
        dribbles: {
          attempts: 1,
          success: 0,
        },
        duels: {
          total: 16,
          won: 6,
        },
        shots: {
          total: 0,
          on: 0,
        },
        fouls: {
          drawn: 2,
          committed: 4,
        },
        tackles: {
          total: 3,
          blocks: 0,
          interceptions: 1,
        },
        minutesPlayed: 118,
      },
    },
    {
      href: "/players/nahuel-molina",
      firstName: "Nahuel",
      lastName: "Molina",
      position: "RB",
      number: 26,
      team: "Atletico Madrid",
      age: 24,
      foot: "right",
      careerStats: {
        apps: 31,
        goals: 1,
        assists: 3,
      },
      tournamentStats: {
        gamesPlayed: 7,
        asSubstitute: 1,
        goals: 1,
        assists: 1,
        averageRating: 6.6,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 288,
          key: 3,
          accuracy: 33,
        },
        dribbles: {
          attempts: 2,
          success: 1,
        },
        duels: {
          total: 26,
          won: 9,
        },
        shots: {
          total: 2,
          on: 1,
        },
        fouls: {
          drawn: 0,
          committed: 3,
        },
        tackles: {
          total: 8,
          blocks: 1,
          interceptions: 3,
        },
        minutesPlayed: 568,
      },
    },
    {
      href: "/players/lisandro-martinez",
      firstName: "Lisandro",
      lastName: "Martinez",
      position: "CB",
      number: 25,
      team: "Manchester United",
      age: 24,
      foot: "left",
      careerStats: {
        apps: 15,
        goals: 0,
        assists: 0,
      },
      tournamentStats: {
        gamesPlayed: 5,
        asSubstitute: 3,
        goals: 0,
        assists: 0,
        averageRating: 6.8,
        cards: {
          yellow: 1,
          red: 0,
        },
        passes: {
          total: 153,
          key: 1,
          accuracy: 26,
        },
        dribbles: {
          attempts: 1,
          success: 0,
        },
        duels: {
          total: 18,
          won: 12,
        },
        shots: {
          total: 0,
          on: 0,
        },
        fouls: {
          drawn: 3,
          committed: 2,
        },
        tackles: {
          total: 6,
          blocks: 1,
          interceptions: 3,
        },
        minutesPlayed: 301,
      },
    },
    {
      href: "/players/nicolas-tagliafico",
      firstName: "Nicolas",
      lastName: "Tagliafico",
      position: "LB",
      number: 3,
      team: "Ajax",
      age: 30,
      foot: "left",
      careerStats: {
        apps: 50,
        goals: 1,
        assists: 0,
      },
      tournamentStats: {
        gamesPlayed: 6,
        asSubstitute: 3,
        goals: 0,
        assists: 0,
        averageRating: 6.6,
        cards: {
          yellow: 0,
          red: 0,
        },
        passes: {
          total: 143,
          key: 2,
          accuracy: 20,
        },
        dribbles: {
          attempts: 2,
          success: 0,
        },
        duels: {
          total: 27,
          won: 17,
        },
        shots: {
          total: 3,
          on: 2,
        },
        fouls: {
          drawn: 6,
          committed: 6,
        },
        tackles: {
          total: 7,
          blocks: 1,
          interceptions: 9,
        },
        minutesPlayed: 372,
      },
    },
    {
      href: "/players/german-pezzella",
      firstName: "German",
      lastName: "Pezzella",
      position: "CB",
      number: 6,
      team: "Fiorentina",
      age: 31,
      foot: "right",
      careerStats: {
        apps: 38,
        goals: 3,
        assists: 0,
      },
      tournamentStats: {
        gamesPlayed: 3,
        asSubstitute: 3,
        goals: 0,
        assists: 0,
        averageRating: 6.2,
        cards: {
          yellow: 1,
          red: 0,
        },
        passes: {
          total: 44,
          key: 0,
          accuracy: 14,
        },
        dribbles: {
          attempts: 0,
          success: 0,
        },
        duels: {
          total: 10,
          won: 2,
        },
        shots: {
          total: 1,
          on: 0,
        },
        fouls: {
          drawn: 2,
          committed: 2,
        },
        tackles: {
          total: 0,
          blocks: 0,
          interceptions: 0,
        },
        minutesPlayed: 57,
      },
    },
    {
      href: "/players/juan-foyth",
      firstName: "Juan",
      lastName: "Foyth",
      position: "CB",
      number: 2,
      team: "Villarreal",
      age: 24,
      foot: "right",
      careerStats: {
        apps: 18,
        goals: 0,
        assists: 0,
      },
      tournamentStats: {
        gamesPlayed: 1,
        asSubstitute: 1,
        goals: 0,
        assists: 0,
        averageRating: 6.7,
        cards: {
          yellow: 2,
          red: 0,
        },
        passes: {
          total: 575,
          key: 2,
          accuracy: 75,
        },
        dribbles: {
          attempts: 1,
          success: 1,
        },
        duels: {
          total: 65,
          won: 36,
        },
        shots: {
          total: 1,
          on: 0,
        },
        fouls: {
          drawn: 5,
          committed: 13,
        },
        tackles: {
          total: 0,
          blocks: 0,
          interceptions: 0,
        },
        minutesPlayed: 4,
      },
    },
  ],
  goalkeepers: [
    {
      href: "/players/emiliano-martinez",
      firstName: "Emiliano",
      lastName: "Martinez",
      position: "GK",
      number: 23,
      team: "Aston Villa",
      age: 30,
      foot: "right",
      careerStats: {
        apps: 31,
        cleanSheets: 23,
        goalsConceded: 12,
      },
      tournamentStats: {
        gamesPlayed: 7,
        asSubstitute: 0,
        averageRating: 6.8,
        goalsConceeded: 8,
        saves: 7,
        cards: {
          yellow: 1,
          red: 0,
        },
        minutesPlayed: 690,
      },
    },
    {
      href: "/players/franco-armani",
      firstName: "Franco",
      lastName: "Armani",
      position: "GK",
      number: 1,
      team: "River Plate",
      age: 37,
      foot: "right",
      careerStats: {
        apps: 19,
        cleanSheets: 8,
        goalsConceded: 18,
      },
      tournamentStats: {
        gamesPlayed: 0,
        asSubstitute: 0,
        averageRating: null,
        goalsConceeded: 0,
        saves: 0,
        cards: {
          yellow: 0,
          red: 0,
        },
        minutesPlayed: 0,
      },
    },
    {
      href: "/players/geronimo-rulli",
      firstName: "Gerónimo",
      lastName: "Rulli",
      position: "GK",
      number: 12,
      team: "Villarreal",
      age: 30,
      foot: "right",
      careerStats: {
        apps: 4,
        cleanSheets: 3,
        goalsConceeded: 1,
      },
      tournamentStats: {
        gamesPlayed: 0,
        asSubstitute: 0,
        averageRating: null,
        goalsConceded: 0,
        saves: 0,
        cards: {
          yellow: 0,
          red: 0,
        },
        minutesPlayed: 0,
      },
    },
  ],
};
